apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: korona-kiks
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: korona-kiks
    newName: rg.fr-par.scw.cloud/djnd/korona-kiks
    newTag: '5ced83484117c65c55e6bc97c99d212d96856059'