apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: korona-kiks
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: korona-kiks
    newName: rg.fr-par.scw.cloud/djnd/korona-kiks
    newTag: '8754dd9cd78f1c4454787355c61e3729c0b628ae'